### ISSUE TITLE
Tercera Entrega

### ISSUE THREAD

**Issue by diegosanchez** [bustamante-jt/tp2n3#10]
- [x] Ubico un algoformer, ubico un bonus doble cañón,ubico otro algoformer enemigo, el algoformer captura el bonus y ataca al enemigo verificando que causa el doble de daño durante 10 turnos.

- [x] Repetir para el modo alterno.

- [x] Ubico un algoformer, ubico un bonus burbuja, ubico un otro alfoformer enemigo, el algoformer captura el bonus, el otro algoformer ataca al primer algoformer, este no recibe daños, repetir hasta 2 turnos propios, continuar y verificar que en el 3ro sí reciba daño.

- [x] Realizar el mismo test en modo alterno

- [x] Ubico un algoformer, ubico un bonus flash, verifico que se mueve 3 veces más rápido durante 3 turnos propios.
Repetir en modo alterno
Repetir en modo humanoide-alterno-humanoide

- [x] Test boundary cases (Si ya tiene un bonus de un tipo que no pueda agarrar otro del mismo tipo, Atrapar 2 bonus distintos verifcar ambos comportamientos, etc…)

**Comment by diegosanchez** [comment]
Donde puedo encontrar las pruebas en modo alterno? El lo ultimo q me resta verificar.

**Comment by bustamante-jt** [comment]
La clase BonusTest fue completada con las pruebas unitarias que faltaban.

**Comment by diegosanchez** [comment]
Puede ser que no hayan hecho el push???

**Comment by bustamante-jt** [comment]
No, acá está: https://github.com/bustamante-jt/tp2n3/blob/master/test/fiuba/algo3/modelo/BonusTest.java

**Comment by diegosanchez** [comment]
completa
