### ISSUE TITLE
Diagrama de clases desactualizado 

### ISSUE THREAD

**Issue by diegosanchez** [bustamante-jt/tp2n3#12]
[Cuarta Entrega](https://github.com/bustamante-jt/tp2n3/issues/11#issuecomment-230594688)

El casillero tiene un contenido, Nada, Chispa y Bonus heredan de esta clase.

Por favor, actualicen el diagrama de clases.

**Comment by bustamante-jt** [comment]
Hola Diego, no estoy seguro de a qué te referís. El diagrama de clases muestra que la clase Casillero tiene un atributo de la clase Contenido, la cual es una clase abstracta (Chispa, Algoformer, Bonus y Nada heredan de ella). En el diagrama "Contenido Jerarquía" se puede ver esa herencia y en el diagrama "Diagrama Global" se ve la relación entre Casillero y los distintos tipos de contenido.

**Comment by diegosanchez** [comment]
[image: Inline images 1]

Este diagrama esta mal.  Se entiende que casillero tiene instancias de:
Chispa, Nada, Bonus

2016-07-05 20:04 GMT-03:00 Tomás Bustamante <notifications@github.com>:

> Hola Diego, no estoy seguro de a qué te referís. El diagrama de clases
> muestra que la clase Casillero tiene un atributo de la clase Contenido, la
> cual es una clase abstracta (Chispa, Algoformer, Bonus y Nada heredan de
> ella). En el diagrama "Contenido Jerarquía" se puede ver esa herencia y en
> el diagrama "Diagrama Global" se ve la relación entre Casillero y los
> distintos tipos de contenido.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bustamante-jt/tp2n3/issues/12#issuecomment-230628281>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADwJD_RmOCvPAareEU5yLZfDcf-PDAvWks5qSuMIgaJpZM4JFhzl>
> .
>



-- 
Saludos
DiegoS

------


Diego Sanchez
[image: http://]about.me/sanchez.diego
<http://about.me/sanchez.diego?promo=email_sig>

**Comment by bustamante-jt** [comment]
Actualizado.
