### ISSUE TITLE
Relación Circular

### ISSUE THREAD

**Issue by diegosanchez** [bustamante-jt/tp2n3#3]
*Algoformer* conoce a *cacillero* y viceversa.  No es deseable. Podemos eliminarla?

**Comment by bustamante-jt** [comment]
Algoformer no conoce a casillero. Solamente el casillero conoce a Algoformer.

**Comment by diegosanchez** [comment]
Luego ví el código y ví que en efecto es así.  En el diagrama de clases está la inconsistencia
