### ISSUE TITLE
Nombre test

### ISSUE THREAD

**Issue by diegosanchez** [bustamante-jt/tp2n3#4]
https://github.com/bustamante-jt/tp2n3/blob/master/test/fiuba/algo3/modelo/PruebasAlgoformers.java#L143

No evidencia el caso de uso.

El caso de uso sería:

**Optimous ataca a Megatron y este ve sus puntos disminuidos tantas veces como el ataque de Optimous vale.**

**Comment by bustamante-jt** [comment]
Corregido.
