### ISSUE TITLE
Segunda Entrega

### ISSUE THREAD

**Issue by diegosanchez** [bustamante-jt/tp2n3#9]
- [x] Llenar una zona rocosa, verificar que todos los algoformers en todos sus modos la atraviesen sin problemas (**bien**)
- [x] Llenar una zona pantano, verificar que en modo humanoide no se pueda atravesar. (**bien**)
- [x] LLenar una zona pantano, verificar que en modo alterno las unidades terrestres tardan el doble que rocoso (**bien**)
- [x] LLenar una zona pantano, verificar que las unidades aéreas las atraviesan sin problemas (**bien**)
- [x] Llenar una zona de espinas verificar que todas las unidades terrestres pierden un 5% de sus vida por cada casillero de estos que atraviesen (**bien**)
- [x] LLenar una zona de espinas, verificar que unidades aéreas no tienen problemas al atravesarlas. (*falta*)
- [x] Llenar una zona con nubes, verificar que las unidades aéreas las atraviesan sin problemas (**bien**)
- [x] Llenar una zona de nebulosa de andrómeda, pasar una unidad aérea, corroborar que quede 3 turnos atrapada, sin moverse. (**bien**)
- [x] Llenar una zona de tormenta psiónica, pasar un algoformer alterno aéreo, ver que baje su capacidad de ataque.
test 9 + volver a pasar y ver que no bajó su capacidad de ataque.  (**bien**)

**Comment by diegosanchez** [comment]
Asegurensé de que funciona una nave pasando por zona espinoza. Una ves que esto funcione, cierren el issue.

**Comment by bustamante-jt** [comment]
Listo.
